FROM python:3.13-slim@sha256:ffb752e139c0a19692a43af8d8523b274222dd68eebad5d583b45c2201c6e30a

RUN apt-get update \
    && apt-get install --yes --no-install-recommends g++ libc6-dev ninja-build \
    && rm -rf /var/lib/apt/lists/*
